name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  android:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"
          channel: stable
          cache: true

      - name: Check Flutter Version
        run: flutter --version

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab


  ios:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"
          channel: stable
          cache: true

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Check Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS IPA
        run: flutter build ipa --release

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
